-- Custom artillery shells will automatically be created for anything listed here.
valid_artillery_items = 
{
  "raw-wood",
  "coal",
  "stone",
  "iron-ore",
  "copper-ore",
  "uranium-ore"
}

bobores_valid_artillery_items =
{
  "amethyst-ore",
  "bauxite-ore",
  "cobalt-ore",
  "diamond-ore",
  "emerald-ore",
  "gem-ore",
  "gold-ore",
  "lead-ore",
  "nickel-ore",
  "quartz",
  "ruby-ore",
  "rutile-ore",
  "sapphire-ore",
  "silver-ore",
  "tin-ore",
  "topaz-ore",
  "tungsten-ore",
  "zinc-ore",

  --  "thorium-ore", not yet supported, icon gets generated by bobores
}

fivedim_valid_artillery_items =
{
  "bauxite-ore",
  "gold-ore",
  "lead-ore",
  "tin-ore",
  "zinc-ore",
}

-- Items listed here will get artillery shells with a custom tint.
-- If not present, they will instead get a default red tint on the map,
-- and a vanilla artillery shell icon with the original item icon superimposed.
custom_tints =
{
  ["raw-wood"] = {r = 100, g = 38, b = 13, a = 255},
  ["coal"] = {r = 60, g = 60, b = 60, a = 255},
  ["stone"] = {r = 93, g = 88, b = 73, a = 255},
  ["iron-ore"] = {r = 40, g = 70, b = 100, a = 255},
  ["copper-ore"] = {r = 185, g = 74, b = 32, a = 255},
  ["uranium-ore"] = {r = 0, g = 200, b = 0, a = 255},
}

bobores_custom_tints =
{
  ["amethyst-ore"] = {r = 120, g = 50, b = 80, a = 255},
  ["bauxite-ore"] = {r = 220, g = 195, b = 100, a = 255},
  ["cobalt-ore"] = {r = 40, g = 90, b = 145, a = 255},
  ["diamond-ore"] = {r = 180, g = 190, b = 205, a = 255},
  ["emerald-ore"] = {r = 50, g = 100, b = 42, a = 255},
  ["gem-ore"] = {r = 230, g = 175, b = 120, a = 255},
  ["gold-ore"] = {r = 240, g = 200, b = 50, a = 255},
  ["lead-ore"] = {r = 30, g = 30, b = 30, a = 255},
  ["nickel-ore"] = {r = 105, g = 185, b = 155, a = 255},
  ["quartz"] = {r = 255, g = 255, b = 255, a = 255},
  ["ruby-ore"] = {r = 140, g = 30, b = 30, a = 255},
  ["rutile-ore"] = {r = 145, g = 20, b = 160, a = 255},
  ["sapphire-ore"] = {r = 50, g = 50, b = 200, a = 255},
  ["silver-ore"] = {r = 235, g = 235, b = 255, a = 255},
  ["tin-ore"] = {r = 140, g = 140, b = 140, a = 255},
  ["topaz-ore"] = {r = 255, g = 205, b = 0, a = 255},
  ["tungsten-ore"] = {r = 155, g = 80, b = 30, a = 255},
  ["zinc-ore"] = {r = 80, g = 200, b = 190, a = 255}
}

function table.merge(t1, t2)
  for k,v in ipairs(t2) do
    table.insert(t1, v)
  end

  return t1
end

function table.keyedMerge(t1, t2)

  for k, v in pairs(t2) do
    t1[k] = v
  end

  return t1
end

-- Only add modded items when the mod is also loaded
if mods["5dim_ores"] then
  valid_artillery_items = table.merge(valid_artillery_items, fivedim_valid_artillery_items)
end

if mods.bobores then
  valid_artillery_items = table.merge(valid_artillery_items, bobores_valid_artillery_items)
  custom_tints = table.keyedMerge(custom_tints, bobores_custom_tints)
end

